[package]
name = "tokio-udp-multicast-chat"
version = "0.1.0"
authors = ["Henning Ottesen <henning@live.no>"]

[dependencies]
tokio = "0.1.5"
tokio-io = "0.1.6"
futures = "0.1.21"
socket2 = "0.3.4"
clap = "2.31.2"
